### ISSUE TITLE
Breaks vscode-icons css icon

### ISSUE THREAD

**Issue by dave-irvine** [AndrewLeedham/vscode-modular-css#1]
Once this extension is enabled, css documents no longer have their icon from vscode-icons package.

**Comment by AndrewLeedham** [comment]
This is because the extension defines a new language with the id "modular-css" which [vscode-icons](https://github.com/vscode-icons/vscode-icons/blob/e0cf27f5a68fdd77ae680be1bacf17c1e54b57b6/src/icon-manifest/languages.ts#L37) does not recognise. It would be possible to make the plugin just add a grammar to extend CSS itself, but you won't be able to turn it off, and you would get validation errors unless you turn them off.

I think the logical fix for this is to convert to just adding a grammar, since validation can be turned off per workspace with: `"css.validate": false`.

**Comment by dave-irvine** [comment]
Excuse my ignorance on this one, I have no idea how vscode plugins work, but why is it necessary to define a new language id, can you not just keep css?

Alternatively I guess you open a PR on vscode-icons to get your language ID added to css icon?

**Comment by AndrewLeedham** [comment]
@dave-irvine I did some more research in to the extension system for VSCode (I'm somewhat new to it myself). I have released a new version that simply extends the built in CSS syntax, see the [Changelog](https://github.com/AndrewLeedham/vscode-modular-css/blob/master/CHANGELOG.md) for details.

Let me know if this fixes your vscode-icons issue.

**Comment by dave-irvine** [comment]
Well, certainly the css icon works now, but it seems like the rest of the module does not. I'm getting a syntax error message when I use the "composes" rule which I didn't get with the original release of this extension.

**Comment by AndrewLeedham** [comment]
That is expected. If you add `"css.validate": false` to your workspace settings, that will resolve the issue. Since this is just a highlighter not a validator. The validation was disabled before as the language was completely different to CSS, but it now simple extends it.

**Comment by dave-irvine** [comment]
I'm also not seeing "composes" or ":global" or anything else come up in the autocomplete, so either something is broken or I'm not sure what the extension adds that I should be looking for?

**Comment by AndrewLeedham** [comment]
The extension is purely syntax highlighting, nothing else. It just colours your CSS. Auto-complete and validation may come down the line.
